### ISSUE TITLE
Extend list of domains

### ISSUE THREAD

**Issue by fbormann** [oncase/certbot-route53-acm#1]
I think it would be a great idea if we can provide a list of domains and generate a certificate for each of them.

Like, instead of providing a single DNS we would be able to say: --dns_list a.com, b.com, c.com.

**Comment by marpontes** [comment]
Do you see a limitation for configuring these domains in a file?

I am saying this imagining some scenarios where you could have the following structure:

```yml
aws_account_1:
  id: X
  secret: Y
  us-east-1:
    domain1: cert_arn1
    domain2: cert_arn2
```

... and then a CI//CD process could mount this config to the image that would iterate over the accounts, regions and domains.

After mounted the file, the argument could then be `--DOMAIN-LIST-FILE=/something/files-list.yml`
